# Generated by Django 2.1.2 on 2018-10-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='httpurl',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_id',
            field=models.CharField(max_length=250),
        ),
    ]
